question_data = [
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Science: Computers",
     "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Science: Computers",
     "question": "RAM stands for Random Access Memory.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The first dual-core CPU was the Intel Pentium D.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The Windows ME operating system was released in the year 2000.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Science: Computers",
     "question": "DHCP stands for Dynamic Host Configuration Port.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The Windows 7 operating system has six main editions.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
     "incorrect_answers": ["False"]}
]
